### ISSUE TITLE
features in embedding_widget not working properly

### ISSUE THREAD

**Issue by lufre1** [computational-cell-analytics/micro-sam#517] opened 2024-04-16 08:46 UTC
## Description
while testing the new embedding feature the folowing issues showed up:
- when loading embedding from disk:
    - tile shape and halo ist not displayed  in the dialog but rather the variables containing the values
    - once a embeddings_save_path is chosen you cannot "unchoose"
    - cannot load "untiled" embeddings from disk - error loading tiling information

**Comment by lufre1** [comment] 2024-04-16 13:02
when an embedding save path has been previously chose, choosing nothing (to use in-memory storing for embeddings) leads to following error:
```
--> 863 if (self.embeddings_save_path is not None) and os.listdir(self.embeddings_save_path):
        self.embeddings_save_path is not None = True
        self.embeddings_save_path = ''
        self = <micro_sam.sam_annotator._widgets.EmbeddingWidget object at 0x708469daf490>
    864     try:
    865         f = zarr.open(self.embeddings_save_path, "a")

FileNotFoundError: [Errno 2] No such file or directory: '' 
```

**Comment by constantinpape** [comment] 2024-04-16 13:45
> when an embedding save path has been previously chose, choosing nothing (to use in-memory storing for embeddings) leads to following error:

Ok, thanks for reporting! You can ignore this one for now; I will double check it in the evening.

**Comment by constantinpape** [comment] 2024-04-16 19:24
> when an embedding save path has been previously chose, choosing nothing (to use in-memory storing for embeddings) leads to following error:

I cannot reproduce this. We can look at it together tomorrow.

**Comment by constantinpape** [comment] 2024-04-21 09:50
This is fixed now.

**Closed by constantinpape** 2024-04-21 09:50 UTC
