### ISSUE TITLE
Errors when segmenting 3D slices

### ISSUE THREAD

**Issue by prog96** [computational-cell-analytics/micro-sam#60] opened 2023-06-28 14:04 UTC
I tried to use 3D annotator to segment my 3D data but an error "You either haven't provided any prompts or invalid prompts. The segmentation will be skipped." showed up when I clicked "Segment Slice". I only have these three points on this slice and there are no other points in other slices. How can I solve this?
![image](https://github.com/computational-cell-analytics/micro-sam/assets/74073398/dfc6364f-a1bf-4242-aa4f-0e4ee2b18758)

**Comment by constantinpape** [comment] 2023-06-28 15:25
Hi @prog96,
this error is surprising, since it should only occur when you're using bounding box annotations.
 For reference, it works without problems for me when using the [3d example script](https://github.com/computational-cell-analytics/micro-sam/blob/master/examples/sam_annotator_3d.py):
![3d-seg](https://github.com/computational-cell-analytics/micro-sam/assets/4263537/36184ca9-8fcc-4e4d-afa6-e95d8970a868)
(This is the same situation as in your case, one positive and two negative prompts, no other prompts).
Can you do the following:
- make sure you're using the latest version of `micro_sam` (pull the latest commit from master)
- if that does not fix the problem: try running the example 3d annotation script and see if this shows the same error for you

**Comment by prog96** [comment] 2023-06-29 10:19
I tried to run the example and it worked with your provided dataset but not with mine. I actually added a line of code in annotator_3d.py script to change the order of my dataset dimensions (after changing it became 860 x 860 x 26) before calling annotator_3d function, as the dimensions did not fit when first loaded into the program. Not sure if this causes the problem.

**Comment by constantinpape** [comment] 2023-06-29 10:24
Can you upload your data somewhere? Then I can see if I can reproduce and fix the error. (If you don't want to share it publicly feel free to send a link via mail.)

**Comment by constantinpape** [comment] 2023-06-29 17:19
I have checked your volume and it works for me when using the following script:

```python
import imageio.v3 as imageio
from micro_sam.sam_annotator import annotator_3d

vol = imageio.imread("./002_Liga_Stecker_ABS01_FDK_860_860_26_float_fft_20_8_4.tif")
# NOTE: pass the data with axis ZYX, i.e. with shape (26, 860, 860)
print(vol.shape)
annotator_3d(vol, "./embeddings.zarr")
```

The segmentation tool works as expected with this:
![3d-annotation-debug](https://github.com/computational-cell-analytics/micro-sam/assets/4263537/3e80ad3a-90d6-43d2-9a47-94039a5853e9)

I am not really sure why it doesn't work for you. One possible reason:

> I actually added a line of code in annotator_3d.py script to change the order of my dataset dimensions (after changing it became 860 x 860 x 26)

That is incorrect. The volume needs to have the shape `26 x 860 x 860` (python uses ZYX axis conventions).

**Comment by prog96** [comment] 2023-06-30 07:14
Thank you for the correction. I did not use a library to read the 3D tif file. I corrected it and removed the line for changing the dimensions but another error appeared:

EmitLoopError: calling <psygnal._weak_callback._StrongFunction object at 0x000002C138920310> with args=(False,) caused ValueError: could not broadcast input array from shape (860,26) into shape (860,860).

**Comment by constantinpape** [comment] 2023-06-30 07:17
Most likely you have still the cached embeddings. Please remove the cached embeddings (corresponding to the `embeddings.zarr` path in the script I shared) and rerun.

**Comment by prog96** [comment] 2023-07-04 08:00
It works well now, thank you! 

Do you have any tips on how to place points on these two black pores? Are these pores too small to do that or it is still possible to do it by trial and error?

![image](https://github.com/computational-cell-analytics/micro-sam/assets/74073398/9dced974-86e4-427f-9cb3-df50b45c2e39)

**Comment by constantinpape** [comment] 2023-07-05 06:49
> It works well now, thank you!

Great!

> Do you have any tips on how to place points on these two black pores?

I would try using bounding box annotations first, and only use points if the pores are not correctly found from the bounding box.

> Are these pores too small to do that or it is still possible to do it by trial and error?

They might be a bit too small. In this case you could try to use tiling to improve results. (For how to use tiling please refer to the doc-string of the annotator functions; I will also try to document this better next weeks).

**Comment by prog96** [comment] 2023-07-07 08:31
Is tiling also helpful in 3D segmentation for small pores?

**Comment by constantinpape** [comment] 2023-07-07 17:36
Yes, it should help in that case.

**Comment by constantinpape** [comment] 2023-07-09 18:47
Closing this because the error is solved. Please open a new issue if some other error or questions come up.
I will add some documentation on the tiling in the next 1 or 2 weeks.

**Closed by constantinpape** 2023-07-09 18:47 UTC
