### ISSUE TITLE
Errors when running micro-sam.annotator2d

### ISSUE THREAD

**Issue by MihaelaCroitor** [computational-cell-analytics/micro-sam#57] opened 2023-06-22 22:26 UTC
I have downloaded anaconda and followed the given steps: cloned the micro-sam directory, created a cpu-based environment using mamba and once activated, installed napari using 'pip install e .'. When I run the command 'micro_sam.annotator_2d -i C:\Users\scmc\Desktop\test.png', the napari app opens up with the correct functionality. Still, I get 2 errors:

1. `napari.manifest -> 'skan' could not be imported: Could not find file 'napari.yaml' in module 'skan'`
2. `RuntimeWarning: invalid value encountered in cast!`

I just read a previous issue ticket, so I am not concerned about the first issue. However, every time I click on the image/software, I get the 2nd error. Is that a problem? If so, how would I fix it?

More info about my settings:

```
 active environment : sam
    active env location : C:\Users\scmc\anaconda3\envs\sam
            shell level : 2
       user config file : C:\Users\scmc\.condarc
 populated config files : C:\Users\scmc\.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __win=0=0
       base environment : C:\Users\scmc\anaconda3  (writable)
      conda av data dir : C:\Users\scmc\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\scmc\anaconda3\pkgs
                          C:\Users\scmc\.conda\pkgs
                          C:\Users\scmc\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\scmc\anaconda3\envs
                          C:\Users\scmc\.conda\envs
                          C:\Users\scmc\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by constantinpape** [comment] 2023-06-22 22:35
Hi @MihaelaCroitor,
neither of the two messages should actually cause problems, and neither of them are things we can fix here. (First one is caused by `skan` and the second one by `napari`; and it only occurs in some version, you may be able to get rid of it by updating to a newer napari version).

So in summary: you an ignore these error messages. Does anything in the tool actually not work as expected?

**Comment by constantinpape** [comment] 2023-07-11 09:23
These issues can be fixed by updating to the latest versions of napari (0.4.18) and skan (0.11.1).
I will close this, feel free to reopen if another issue occurs.

**Closed by constantinpape** 2023-07-11 09:23 UTC
